### ISSUE TITLE
Де знайти детальний опис характеристик?

### ISSUE THREAD

**Issue by AndrejGorodnij** [yaroslavshostak/api_docs#2]
В [документації](https://api-docs-v2.readthedocs.io/ru/latest/dom_ria/search.html) вказано:

Тип пропозиції | characteristic[1437] | Number

Та надано приклад:

**Тип пропозиції - від посередника**
і в самому УРЛ - `&characteristic[1437]=1434`

Де я можу знайти список параметрів кожної характеристики? Бо я не дуже зрозумів звідки взялось 1434, і які ще є варіанти... довелось реверсінжирити запити з веб-сайту, але я не впевнений що це працюватиме.

**Comment by yaroslavshostak** [comment]
Доброго дня.
Опис характеристик нерухомості можна знайти за посиланням: 
https://api-docs-v2.readthedocs.io/ru/latest/dom_ria/house-characteristics.html

**Comment by AndrejGorodnij** [comment]
Дякую, вибачте, відкривав сторінку, побачив що на початку були технічні характеристики, думав характеристики фільтру в іншому якомусь розділі.

Дякую за інформацію, ще раз вибачте що потурбував, був неуважним.
