### ISSUE TITLE
Full advertisement `main_photo` URL in DOM.RIA

### ISSUE THREAD

**Issue by AndrejGorodnij** [yaroslavshostak/api_docs#3]
I can't access to advertisements photos, server returns JSON like this (this is real data fragmen), and it doesn't show server domain, that stored files.

```
"207039746":{
   "id":207039746,
   "parent_photo_id":207039746,
   "ordering":2,
   "file":"dom/photo/20703/2070397/207039746/207039746.jpg"
},
```

What domain is used to store a photos? I have tried `https://dom.ria.com/` (it return 404), and `https://cdn.riastatic.com/photos/`, that returns `415 Unsupported Media Type`

So how can I get full photo url?

**Comment by Liudmyla-Ortynska** [comment]
Hello, please insert the xl prefix before .jpg 
your example: https://cdn.riastatic.com/photos/dom/photo/20703/2070397/207039746/207039746xl.jpg

**Comment by AndrejGorodnij** [comment]
Thanks. It isn't quiet easy to understand why this works like that... but it works... Thank you.
